/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package antrianklinik;

/**
 *
 * @author PUTRI ANASTASYA
 */

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import java.util.Queue;
import java.awt.event.KeyEvent;


class Patient<T> {
    private String nama;
    private String nik;
    private String nomorAntrian;
    private T layanan;

    public Patient(String nama, String nik, String nomorAntrian, T layanan) {
        this.nama = nama;
        this.nik = nik;
        this.nomorAntrian = nomorAntrian;
        this.layanan = layanan;
    }

    // Getter methods
    public String getNama() {
        return nama;
    }

    public String getNIK() {
        return nik;
    }

    public String getNomorAntrian() {
        return nomorAntrian;
    }

    public T getLayanan() {
        return layanan;
    }
}


public class AntrianKlinik extends javax.swing.JFrame {

    private Queue<Patient<String>> antrianUmum = new LinkedList<>();
    private Queue<Patient<String>> antrianGigi = new LinkedList<>();
    
    private int counterUmum = 1; // Counter untuk antrian umum
    private int counterGigi = 1; // Counter untuk antrian gigi
    private int jumlahPasien = 0;
    /**
     * Creates new form AntrianKlinik
     */
    public AntrianKlinik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textNIK = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnTambah = new javax.swing.JButton();
        btnPanggilUmum = new javax.swing.JButton();
        btnPanggilGigi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTampilan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textUmum = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textGigi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        textJumlah = new javax.swing.JLabel();

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Pasien Umum");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Pasien Gigi");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ANTRIAN KLINIK UB");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Pasien");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pilihan Layanan");

        textNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNIKActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Pasien Umum");

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("Pasien Gigi");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        btnTambah.setText(" Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnPanggilUmum.setText("Panggil Pasien Umum");
        btnPanggilUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanggilUmumActionPerformed(evt);
            }
        });

        btnPanggilGigi.setText("Panggil Pasien Gigi");
        btnPanggilGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanggilGigiActionPerformed(evt);
            }
        });

        textTampilan.setColumns(20);
        textTampilan.setRows(5);
        jScrollPane1.setViewportView(textTampilan);

        textUmum.setColumns(20);
        textUmum.setRows(5);
        jScrollPane2.setViewportView(textUmum);

        textGigi.setColumns(20);
        textGigi.setRows(5);
        jScrollPane3.setViewportView(textGigi);

        jLabel5.setText("Daftar Antrian");

        jLabel6.setText("Panggilan Antrian Pasien Umum");

        jLabel7.setText("Panggilan Antrian Pasien Gigi");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah Pasien Hari Ini : ");

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton2))
                                .addComponent(textNama, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(textNIK))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(textJumlah)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPanggilUmum)
                                .addGap(18, 18, 18)
                                .addComponent(btnPanggilGigi))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(btnReset))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanggilUmum)
                    .addComponent(btnPanggilGigi)
                    .addComponent(btnTambah))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnReset)
                    .addComponent(textJumlah))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNIKActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnPanggilUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilUmumActionPerformed
         String text = textTampilan.getText();
    if (text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Antrian kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String[] lines = text.split("\n");
    StringBuilder newText = new StringBuilder();
    boolean found = false;
    for (String line : lines) {
        if (!found && line.contains("A-")) {
            textUmum.setText(line);
            found = true;
        } else {
            newText.append(line).append("\n");
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "Tidak ada antrian umum", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }

    textTampilan.setText(newText.toString());
    }//GEN-LAST:event_btnPanggilUmumActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      String nama = textNama.getText();
        String nik = textNIK.getText();
        String nomorAntrian = "";

        // Validasi untuk memastikan textNama dan textNIK tidak kosong
        if (nama.isEmpty() || nik.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama dan NIK harus diisi", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi untuk memastikan textNIK berbentuk angka
        try {
            Long.parseLong(nik);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "NIK harus berupa angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi untuk memastikan salah satu radio button dipilih
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
            JOptionPane.showMessageDialog(this, "Pilih jenis layanan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (jRadioButton1.isSelected()) {
            nomorAntrian = "A-" + counterUmum;
            antrianUmum.add(new Patient<>(nama, nik, nomorAntrian, "Umum"));
            counterUmum++;
        } else if (jRadioButton2.isSelected()) {
            nomorAntrian = "C-" + counterGigi;
            antrianGigi.add(new Patient<>(nama, nik, nomorAntrian, "Gigi"));
            counterGigi++;
        }

        textTampilan.append("Nama: " + nama + ", NIK: " + nik + ", Nomor Antrian: " + nomorAntrian + "\n");
        simpanData(nama, nik, nomorAntrian);

        jumlahPasien++; // Menambah jumlah pasien

        // Menampilkan jumlah pasien pada textJumlah
        textJumlah.setText(String.valueOf(jumlahPasien));

        textNama.setText("");
        textNIK.setText("");
        buttonGroup1.clearSelection();
    
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnPanggilGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilGigiActionPerformed
      String text = textTampilan.getText();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Antrian kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String[] lines = text.split("\n");
        StringBuilder newText = new StringBuilder();
        boolean found = false;
        for (String line : lines) {
            if (!found && line.contains("C-")) {
                textGigi.setText(line);
                found = true;
            } else {
                newText.append(line).append("\n");
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Tidak ada antrian gigi", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

        textTampilan.setText(newText.toString());
    }//GEN-LAST:event_btnPanggilGigiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      jumlahPasien = 0;
               // Reset semua field lainnya
        textTampilan.setText("");
        textUmum.setText("");
        textGigi.setText("");
        textNama.setText("");
        textNIK.setText("");
        textJumlah.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

     private void simpanData(String nama, String nik, String nomorAntrian) {
           try (BufferedWriter writer = new BufferedWriter(new FileWriter("daftarAntrian.txt", true))) {
            writer.write("Nama: " + nama + ", NIK: " + nik + ", Nomor Antrian: " + nomorAntrian);
            writer.newLine();
        } catch (IOException e) {
            System.err.println("Gagal menyimpan data: " + e.getMessage());
        }
    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntrianKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntrianKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntrianKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntrianKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AntrianKlinik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanggilGigi;
    private javax.swing.JButton btnPanggilUmum;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textGigi;
    private javax.swing.JLabel textJumlah;
    private javax.swing.JTextField textNIK;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextArea textTampilan;
    private javax.swing.JTextArea textUmum;
    // End of variables declaration//GEN-END:variables
}
